### ISSUE TITLE
database or migration not found

### ISSUE THREAD

**Issue by mepawan** [johndavedecano/PHPLaravelPokerPointingSystem#1]
Hi,
I'm using this project but I didn't find database or laravel migration files. 

can you please provide either database sql file or migration files. 

this will be really great help. 

thanks,

**Comment by johndavedecano** [comment]
dump.sql

**Comment by mepawan** [comment]
Hello Sir,

I didn't find dump.sql file in this repository. There is 'production.sqlite' file inside app/database/ but its blank. 

can you please upload dump.sql file

Thanks you so much.
